version: '3.4'

services:
  vogcodechallenge.api:
    image: ${DOCKER_REGISTRY-}vogcodechallengeapi
    build:
      context: .
      dockerfile: VogCodeChallenge.API/Dockerfile
    
  # When I run this step on my machine 
  # I get the following error
  # Severity	Code	Description	Project	File	Line	Suppression State
  # Error	CTC1031	Linux containers are not supported for ConsoleApp1 project.	docker-compose	
  # C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	303	

  #consoleapp1:
  #  image: ${DOCKER_REGISTRY-}consoleapp1
  #  build:
  #    context: .\ConsoleApp1
  #    dockerfile: Dockerfile

